parameters:
#    ua_uc_rua_project2.example.class: uaUCR\uaProject2Bundle\Example

services:
#    ua_uc_rua_project2.example:
#        class: %ua_uc_rua_project2.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
